### PR TITLE
5514 add account number masking to pay-api

### PR DESCRIPTION
**Pull request by sutherlanda**
*Issue #:* 5514
https://github.com/bcgov/entity/issues/5514

*Description of changes:*

*Checklist:*
I confirm that below checklist items are addressed in this pull request; (check the boxes applicable)
- [ ] No lint errors
- [ ] No test case failures and proper coverage for all modules/classes
- [ ] Updated the deployment configs for new environment variable(s)
- [ ] Updated the postman collection in entity repository (https://github.com/bcgov/entity/tree/master/api-e2e/postman) for e2e tests

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-pay license (Apache 2.0).

### CODE REVIEW

**Review by sumesh-aot — COMMENTED** [review]
There are lint errors, and missing test cases. As discussed, we need to handle this based on the user role.

**Comment by sutherlanda** [comment]
> There are lint errors, and missing test cases. As discussed, we need to handle this based on the user role.

The listing error (singular) is corrected. 

The last discussion we had on this, you were going to check with Saravan:

"I think currently the auth system calls this service with system account, that also needs to be changed to pass in user token
need to check with saravan"

If you would like me to do that, just say so, but as of now I am no aware of what solution you would like to be put in place.  I will add test cases once there is a full solution.

**Comment by sumesh-aot** [comment]
> "I think currently the auth system calls this service with system account, that also needs to be changed to pass in user token

Yes, that's correct. We need to factor in changes to permissions in auth side. Also auth needs to pass in the user token instead of a service account token. We don't have a separate ticket to handle this on auth side. 
And as I discussed, this task needs some discussion with team and proper solution starting from the auth side and I don't think the nature of this ticket allows to work independently.

**Comment by saravanpa-aot** [comment]
This task is handled in other tickets.so closing the PR for now.

**Pull request closed without merging**
