### PR TITLE
21464 - Resync EFT branch with main

### PR DESCRIPTION
**Pull request by seeker25**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the sbc-pay license (Apache 2.0).

### CODE REVIEW

**Comment by seeker25** [comment]
Just some deps and some CI to fix

**Comment by seeker25** [comment]
Note: This needs to be merged with non squash, that way it wont cause merge conflicts

**Comment by seeker25** [comment]
Both of the failures are some weird bug due to 4 pm. Will re-run tomorrow.

**Review by Jxio — APPROVED** [review]
LGTM

**Pull request merged**
